// Auto-generated by UnifyWeaver
using System;
using System.Linq;
using UnifyWeaver.QueryRuntime;

namespace UnifyWeaver.Generated
{
    public static class TestLinkQueryModule
    {
        public static (InMemoryRelationProvider Provider, QueryPlan Plan) Build()
        {
            var provider = new InMemoryRelationProvider();
            provider.AddFact(new PredicateId("test_fact", 2), "alice", "bob");
            provider.AddFact(new PredicateId("test_fact", 2), "bob", "charlie");
            var plan = new QueryPlan(
                new PredicateId("test_link", 2),
                new ProjectionNode(new JoinNode(new RelationScanNode(new PredicateId("test_fact", 2)), new RelationScanNode(new PredicateId("test_fact", 2)), (left, right) => Equals(left[1], right[0]), (left, right) => new object[]{ left[0], left[1], right[0], right[1] }), tuple => new object[]{ tuple[0], tuple[3] }),
                false
            );
            return (provider, plan);
        }
    }
}
