#!/usr/bin/awk -f
# Generated by UnifyWeaver v0.0.3
# Target: AWK
# Generated: 2025-12-09 13:43:30
# Predicate: high_value_electronics/3
# Input format: tsv

BEGIN { FS = "	" }
{
    if (($3 > 500)) {
        print $0
    }
}