#!/bin/bash
# Test runner for generated advanced recursion scripts - explicit MODE
# AUTO-GENERATED BY INFERENCE - DO NOT EDIT MANUALLY
#
# Generated by: test_runner_inference.pl
# To regenerate: swipl -g "use_module(unifyweaver(core/advanced/test_runner_inference)), generate_test_runner_inferred, halt."

echo "=== Testing Generated Bash Scripts ==="
echo ""

# Test ancestor.sh (multi-function: 3 functions)
if [[ -f ancestor.sh ]]; then
    echo "--- Testing ancestor.sh ---"
    source ancestor.sh

    # Function: ancestor
    echo "Test 1: Generic test"
    ancestor "test_value" "test_value"

    echo ""
    # Function: ancestor_check
    echo "Test 1: Generic test"
    ancestor_check "test_value" "test_value"

    echo ""
    # Function: ancestor_all
    echo "Test 1: Generic test"
    ancestor_all "test_value"

    echo ""
fi

# Test parent.sh
if [[ -f parent.sh ]]; then
    echo "--- Testing parent.sh ---"
    source parent.sh

    echo "Test 1: Generic test"
    parent 

    echo ""
fi


echo "=== All Tests Complete ==="
