#!/usr/bin/env swipl

% Generated by UnifyWeaver v0.1
% Target: Prolog (SWI-Prolog)
% Compilation: interpreted
% Generated: 2025-12-09 14:01:38
% Predicates: 2
% 

% Set up UnifyWeaver runtime library search path
:- multifile user:file_search_path/2.
:- dynamic user:file_search_path/2.

setup_unifyweaver_path :-
    getenv('UNIFYWEAVER_HOME', Home), !,
    asserta(user:file_search_path(unifyweaver, Home)).
setup_unifyweaver_path.

:- setup_unifyweaver_path.


% === User Code (Transpiled) ===


factorial(0, 1) :-
    !.

factorial(A, B) :-
    A>0,
    C is A+ -1,
    factorial(C, D),
    B is A*D.


run_test :-
    factorial(5, A),
    format('Factorial of 5 is ~w~n', [A]).



% === Entry Point ===

main :-
    run_test,
    halt(0).

main :-
    format(user_error, 'Error: Execution failed~n', []),
    halt(1).

:- initialization(main, main).
